name: TemplateUIKit
options:
  bundleIdPrefix: com.example
targets:
  TemplateUIKit:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: Sources
    settings:
      base:
        INFOPLIST_FILE: Sources/Info.plist
        GENERATE_INFOPLIST_FILE: false
        MARKETING_VERSION: 1.0.0
        CURRENT_PROJECT_VERSION: 1
        LD_RUNPATH_SEARCH_PATHS: $(inherited) @executable_path/Frameworks
        TARGETED_DEVICE_FAMILY: "1,2" # iPhone and iPad
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        DEVELOPMENT_ASSET_PATHS: ""
